Repository pagopa/pagopa-fdr-xml-to-json, pull requests merged in 2024-05, with the labels that each got.

#7 feat: NOD-861 rivedere function fdr
  pom.xml
  src/main/java/it/gov/pagopa/fdrxmltojson/FdrXmlToJson.java
  src/main/openapi/openapi_internal.json
Labels: bug, size/large, breaking-change, patch

#8 [NOD-836] feat: handle errors during data migration
  README.md
  host.json
  pom.xml
  src/main/java/it/gov/pagopa/fdrxmltojson/FdrXmlToJson.java
Labels: size/small, patch

#9 [NOD-847] fix: resolved error on psp name
  pom.xml
  src/main/java/it/gov/pagopa/fdrxmltojson/FdrXmlToJson.java
Labels: bug, size/small

#10 feat: NOD-892 implementazione j unit
  pom.xml
  src/main/java/it/gov/pagopa/fdrxmltojson/FdrXmlError.java
  src/test/java/FdrXmlErrorTest.java
  src/test/java/FdrXmlToJsonTest.java
  src/test/java/InfoTest.java
  src/test/java/util/LogHandler.java
  src/test/java/util/MockHttpURLConnection.java
  src/test/java/util/MockURLStreamHandler.java
  src/test/java/util/MockURLStreamHandlerFactory.java
  src/test/java/util/TestUtil.java
  src/test/resources/events/event_ok_1.json
  src/test/resources/xmlcontent/nodoInviaFlussoRendicontazione.xml
Labels: ignore-for-release, size/large
