Repository pagopa/pagopa-fdr-xml-to-json, pull requests merged in 2025-04, with the labels that each got.

#20 fix: [PAGOPA-2716] manual integration test placeholder readme
  integration-test/README.md
Labels: size/small, skip

#22 fix: Readme & GHAs
  .github/workflows/03_code_review.yml
  README.md
  pom.xml
Labels: size/small, skip

#21 chore: [PAGOPA-2960] Fix oom
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/fdrxmltojson/BlobTriggerFn.java
  src/main/java/it/gov/pagopa/fdrxmltojson/FdrXmlCommon.java
  src/main/java/it/gov/pagopa/fdrxmltojson/FdrXmlError.java
  src/main/java/it/gov/pagopa/fdrxmltojson/HttpTriggerFn.java
  src/main/java/it/gov/pagopa/fdrxmltojson/QueueTriggerFn.java
  src/main/java/it/gov/pagopa/fdrxmltojson/util/FormatterUtil.java
  src/main/java/it/gov/pagopa/fdrxmltojson/util/XMLParser.java
  src/main/java/it/gov/pagopa/fdrxmltojson/util/XMLUtil.java
  src/test/java/it/gov/pagopa/fdrxmltojson/HttpTriggerFnTest.java
  src/test/java/it/gov/pagopa/fdrxmltojson/QueueTriggerFnTest.java
Labels: size/large, patch

#24 coverage
  src/test/java/it/gov/pagopa/fdrxmltojson/QueueTriggerFnTest.java
Labels: ignore-for-release, size/small

#26 fix: resolved error on `/info` API
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/fdrxmltojson/Info.java
Labels: bug, size/small, patch

#27 fix: Post Release [PAGOPA-2984]
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/fdrxmltojson/util/FdR3ClientUtil.java
Labels: size/small, patch

#28 fix: [PAGOPA-2984] Fix error trigger
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  host.json
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/fdrxmltojson/BlobTriggerFn.java
  src/main/java/it/gov/pagopa/fdrxmltojson/FdrXmlCommon.java
  src/main/java/it/gov/pagopa/fdrxmltojson/FdrXmlError.java
  src/main/java/it/gov/pagopa/fdrxmltojson/HttpTriggerFn.java
  src/main/java/it/gov/pagopa/fdrxmltojson/Info.java
  src/main/java/it/gov/pagopa/fdrxmltojson/model/BlobData.java
  src/main/java/it/gov/pagopa/fdrxmltojson/model/ErrorRecoveryRequest.java
  src/main/java/it/gov/pagopa/fdrxmltojson/model/ErrorRecoveryResponse.java
  src/main/java/it/gov/pagopa/fdrxmltojson/util/GZipUtil.java
  src/main/java/it/gov/pagopa/fdrxmltojson/util/XMLParser.java
  src/test/java/it/gov/pagopa/fdrxmltojson/BlobTriggerFnTest.java
  src/test/java/it/gov/pagopa/fdrxmltojson/FdrXmlErrorTest.java
  src/test/java/it/gov/pagopa/fdrxmltojson/HttpTriggerFnTest.java
  src/test/java/it/gov/pagopa/fdrxmltojson/util/TestUtil.java
Labels: patch

#30 fix: heap in prod
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
Labels: size/small, patch
